namespace: fullstack-app

# =====================
# Ingress Configuration
# =====================
ingress:
  enabled: true
  host: localhost   # or your Minikube IP if not using localhost

# =====================
# MySQL Configuration
# =====================
mysql:
  image: mysql:8.0
  rootPassword: pwd
  database: userdbexam3
  service:
    port: 3306
    type: ClusterIP

# =====================
# Backend Configuration
# =====================
backend:
  image: bojanapallimeenapadmasiri/k8-backend3:latest
  replicas: 2
  port: 1955
  nodePort: 30028
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

# =====================
# Frontend Configuration
# =====================
frontend:
  image: bojanapallimeenapadmasiri/k8-frontend3:latest
  replicas: 2
  port: 80
  nodePort: 30086
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

  # Point frontend to backend service
  apiUrl: "/api"